FROM node:14 AS BUILD

WORKDIR /home/node/app

# npm ci cannot be used because the package-lock.json file is missing
COPY package*.json ./
RUN npm i

COPY .. .
RUN npm run build --prod

FROM nginx:1.19 AS SERVE

COPY --from=BUILD --chown=www-data:www-data /home/node/app/dist /usr/share/nginx/html
