services:
  bujufix-backend:
    build:
      target: DEV
      context: ./backend
    working_dir: /backend
    volumes:
      - ./backend/:/backend
      - /backend/node_modules
      - db:/database/run/mysqld


  bujufix-frontend:
    build:
      target: DEV
      context: ./frontend
    volumes:
      - ./frontend/:/frontend
      - /frontend/node_modules

  proxy:
    volumes:
      - /backend
      - ./proxy/nginx_dev.conf:/etc/nginx/nginx.conf
      - ./proxy/nginx_dev.conf:/etc/nginx/conf.d/default.conf