services:
  bujufix-backend:
    build:
      context: ./backend
    volumes:
     - ./backend/:/backend
     - /backend/node_modules

  bujufix-frontend:
    build:
      context: ./frontend
    volumes:
      - ./frontend/:/frontend
      - /frontend/node_modules