services:
  bujufix-backend:
    depends_on:
      - bujufix-db
    build:
      context: ./backend
    restart: unless-stopped
    networks:
      - bujufix
    volumes:
     - ./backend/:/backend
     - /backend/node_modules

  bujufix-frontend:
    build:
      context: ./frontend
    depends_on:
      - bujufix-backend
    restart: unless-stopped
    networks:
      - bujufix
    volumes:
      - ./frontend/:/frontend
      - /frontend/node_modules

  bujufix-db:
    image: mariadb
    restart: unless-stopped
    depends_on:
      - proxy
    environment:
      MYSQL_DATABASE: bujufixdb
      MYSQL_USER: buju
      MYSQL_PASSWORD_FILE: /run/secrets/mysql_password
      MYSQL_ROOT_PASSWORD_FILE: /run/secrets/mysql_root_password
    volumes:
      - db:/var/run/mysqld
    network_mode: "none"
    secrets:
      - mysql_password
      - mysql_root_password

  adminer:
    image: adminer
    restart: unless-stopped
    depends_on:
      - bujufix-db
    volumes:
      - db:/var/run/mysqld
    networks:
      - bujufix

  proxy:
    image: nginx
    restart: unless-stopped
    volumes:
      - ./proxy/nginx.conf:/etc/nginx/nginx.conf
      - ./proxy/nginx.conf:/etc/nginx/conf.d/default.conf
    networks:
      - bujufix
    ports:
      - 8000:8000

volumes:
    db:

networks:
  bujufix:

secrets:
    mysql_root_password:
      file: ./db/secrets/mysql_root_password
    mysql_password:
      file: ./db/secrets/mysql_password