services:
  bujufix-backend:
    depends_on:
      - bujufix-db
    build:
      context: ./backend
    restart: unless-stopped
    networks:
      - bujufix
    volumes:
     - db:/database/run/mysqld

  bujufix-frontend:

    depends_on:
      - bujufix-backend
    restart: unless-stopped
    networks:
      - bujufix

  bujufix-db:
    image: mariadb
    restart: unless-stopped
    environment:
      MARIADB_DATABASE_FILE: /run/secrets/mariadb_databasename
      MARIADB_USER_FILE: /run/secrets/mariadb_username
      MARIADB_PASSWORD_FILE: /run/secrets/mariadb_password
      MARIADB_ROOT_PASSWORD_FILE: /run/secrets/mariadb_root_password
    volumes:
      - db:/var/run/mysqld
      - data:/var/lib/mysql
    network_mode: "none"
    secrets:
      - mariadb_password
      - mariadb_root_password
      - mariadb_databasename
      - mariadb_username

  adminer:
    image: adminer
    restart: unless-stopped
    depends_on:
      - bujufix-db
    volumes:
      - db:/var/run/mysqld
    networks:
      - bujufix

  proxy:
    image: nginx
    restart: unless-stopped
    depends_on:
      - bujufix-frontend
    networks:
      - bujufix
    ports:
      - 8000:8000

networks:
  bujufix:

volumes:
  db:
  data:

secrets:
    mariadb_root_password:
      file: db/secrets/mariadb_root_password
    mariadb_password:
      file: db/secrets/mariadb_password
    mariadb_databasename:
      file: db/secrets/mariadb_databasename
    mariadb_username:
      file: db/secrets/mariadb_username