services:
  bujufix-backend:
    build:
      target: PRODUCTION
    working_dir: /backend

  bujufix-frontend:
    image:
      git-registry.thm.de/rgnt06/buju-app:main
    working_dir: /frontend

  proxy:
    volumes:
      - ./proxy/nginx_prod.conf:/etc/nginx/nginx.conf
      - ./proxy/nginx_prod.conf:/etc/nginx/conf.d/default.conf