services:
  bujufix-backend:
    build:
      dockerfile: Dockerfile_dev
    working_dir: /backend
    volumes:
      - ./backend/:/backend
      - /backend/node_modules
      - db:/database/run/mysqld


  bujufix-frontend:
    build:
      dockerfile: Dockerfile_dev
    working_dir: /frontend
    volumes:
      - ./frontend/:/frontend
      - /frontend/node_modules