# base image
FROM node:14

# Create app directory
WORKDIR /backend

# Install app dependencies
COPY package*.json ./

RUN npm install

#RUN npm link morgan

#RUN npm link cors

EXPOSE 8080

CMD [ "npm", "run", "start"]